ERP.WebSite/Controllers/Sys/SysNoticeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCMS.WebSite.Controllers.Sys
{
    public class SysNoticeController : Controller
    {
        Provider.SysNoticeProvider provider = new Provider.SysNoticeProvider();
        // GET: CarBrand
        [Extension.UserAuthorize]
        public ActionResult Index()
        {
            var list = provider.GetList();
            var model = new List<Models.SysNoticeModels.SysNoticeModel>();
            foreach (var item in list)
            {
                model.Add(new Models.SysNoticeModels.SysNoticeModel
                {
                    Id = item.Id,
                    CreateTime=item.CreateTime,
                    Content=item.Content,
                    NoticeType=item.NoticeType,
                    Title=item.Title
                });
            }
            return View(model);
        }

        [Extension.UserAuthorize]
        public ActionResult Create(long? Id)
        {
            var model = new Models.SysNoticeModels.SysNoticeModel();
            if (Id != null)
            {
                var item = provider.GetNotice(Id.Value);
                model = new Models.SysNoticeModels.SysNoticeModel
                {
                    Id = item.Id,
                    CreateTime = item.CreateTime,
                    Content = item.Content,
                    NoticeType = item.NoticeType,
                    Title = item.Title
                };
            }
            return View(model);
        }
        [ValidateInput(false)]
        [Extension.UserAuthorize(ActionName = "Create")]
        public ActionResult Save(Models.SysNoticeModels.SysNoticeModel model)
        {
            var random = Common.PrimaryKey.GetHashCodeID.ToString();
            string FilePath = Common.FileConfig.TempPath + random.Substring(0, 4) + "/" + random.Substring(4) + "/";
            model.Content = MoveContentImage(model.Content, FilePath);
            var group = new UCMS.Entitys.SysNotice()
            {
                Id = model.Id,
                Content=model.Content,
                NoticeType=model.NoticeType,
                Title=model.Title,
                IsDelete = (int)Common.EnumModel.EIsDelete.NotDelete,
                TimeStamp = DateTime.Now,
            };
            var line = provider.Edit(group);
            return Json(new { d = line > 0 ? 1 : 0 });
        }
        public ActionResult Detail(long? Id)
        {
            var model = new Models.SysNoticeModels.SysNoticeModel();
            if (Id != null)
            {
                var item = provider.GetNotice(Id.Value);
                model = new Models.SysNoticeModels.SysNoticeModel
                {
                    Id = item.Id,
                    CreateTime = item.CreateTime,
                    Content = item.Content,
                    NoticeType = item.NoticeType,
                    Title = item.Title
                };
            }
            return View(model);
        }
        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="checkedId"></param>
        /// <returns></returns>
        [Extension.UserAuthorize]
        public ActionResult Delete(string checkedId)
        {
            var ids = new List<long>();
            foreach (var item in checkedId.Split(','))
            {
                ids.Add(Common.ToolHelper.ConvertToLong(item));
            }
            var line = 0;
            if (ids.Count > 0)
            {
                line = provider.Delete(ids);
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }

        /// <summary>
        /// 上传内容图片
        /// </summary>
        /// <returns></returns>
        public ActionResult UploadImage()
        {
            System.Collections.Hashtable hash = new System.Collections.Hashtable();
            try
            {
                string fileTypes = ".gif,.jpg,.jpeg,.png,.bmp,.mp4,.flv,.swf";
                HttpPostedFileBase file = Request.Files["imgFile"];
                if (file != null)
                {
                    string fileExt = System.IO.Path.GetExtension(file.FileName).ToLower();
                    if (string.IsNullOrEmpty(fileExt) || fileTypes.Split(',').ToList().Contains(fileExt))
                    {
                        var ImagesId = string.Empty;
                        var fileMinPath = string.Empty;
                        //文件夹
                        var Folder = string.Empty;
                        //文件ID
                        var FileId = string.Empty;

                        var TempPath = string.Empty;
                        if (fileExt == ".mp4" || fileExt == ".flv" || fileExt == ".swf")
                        {
                            TempPath = Common.FileConfig.VideoPath;
                        }
                        else
                        {
                            TempPath = Common.FileConfig.TempPath;
                        }
                        while (true)
                        {
                            ImagesId = Common.PrimaryKey.GetHashCodeID.ToString();
                            //文件夹
                            Folder = ImagesId.Substring(0, 4) + "/";
                            //文件ID
                            FileId = ImagesId.Substring(4);
                            fileMinPath = Server.MapPath(TempPath + Folder + FileId + fileExt);
                            if (!System.IO.File.Exists(fileMinPath))
                            {
                                break;
                            }
                        }

                        //判断存储文件路径是否存在
                        if (!System.IO.Directory.Exists(this.Server.MapPath(TempPath + Folder)))
                        {
                            System.IO.Directory.CreateDirectory(this.Server.MapPath(TempPath + Folder));
                        }

                        if (fileExt == ".mp4" || fileExt == ".flv" || fileExt == ".swf")
                        {
                            file.SaveAs(fileMinPath);
                            var fileUrl = Url.Content(TempPath + Folder + FileId + fileExt);
                            hash["error"] = 0;
                            hash["url"] = fileUrl;
                        }
                        else
                        {
                            //保存原始图片
                            var fileBigPath = System.IO.Path.GetTempPath() + "BIG-" + ImagesId + fileExt;
                            file.SaveAs(fileBigPath);


                            Image pic = Image.FromFile(fileBigPath);
                            int intWidth = pic.Width;//长度像素值 
                            int intHeight = pic.Height;//高度像素值
                            pic.Dispose();
                            var picWidth = intWidth;
                            var picHeight = intHeight;
                            if (intWidth > 1000 || picHeight > 900)
                            {
                                //图片压缩
                                if (intWidth > intHeight)
                                {
                                    picWidth = 1000;
                                    picHeight = 600;
                                }
                                else
                                {
                                    picWidth = 1000;
                                    picHeight = 900;
                                }
                            }
                            new Common.FileHelper().MakeThumbnail(fileBigPath, fileMinPath, picWidth, picHeight, "W");
                            //删除原始图片
                            if (System.IO.File.Exists(fileBigPath))
                            {
                                System.IO.File.Delete(fileBigPath);
                            }
                            var fileUrl = Url.Content(TempPath + Folder + FileId + fileExt);
                            hash["error"] = 0;
                            hash["url"] = fileUrl;
                        }
                    }
                    else
                    {
                        hash["error"] = 1;
                        hash["message"] = string.Format("上传文件扩展名是不允许的扩展名{0}", fileTypes);
                    }
                }
                else
                {
                    hash["error"] = 1;
                    hash["message"] = "请选择文件";
                }
            }
            catch (Exception ex)
            {
                hash["error"] = 1;
                hash["message"] = "上传错误：" + ex.Message;
            }
            return Json(hash, "text/html", JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// 移动内容图片
        /// </summary>
        /// <param name="content"></param>
        /// <param name="randomNumber"></param>
        string MoveContentImage(string content, string FilePath)
        {
            string result = content;
            var contentList = Common.ToolHelper.GetHtmlImageUrlList(content);
            foreach (var item in contentList)
            {
                if (item.Contains("/Temp/"))
                {
                    if (!string.IsNullOrEmpty(item))
                    {
                        //url虚拟路径处理
                        var path = item;
                        //原文件是否存在
                        FileInfo file = new FileInfo(Server.MapPath(path));
                        if (file.Exists)
                        {
                            //保存到新目录
                            var newFilePath = this.Server.MapPath(FilePath);
                            if (!System.IO.Directory.Exists(newFilePath))
                            {
                                //新目录不存在则创建
                                System.IO.Directory.CreateDirectory(newFilePath);
                            }

ERP.WebSite/Views/SysNotice/Create.cshtml
@{
    //Layout = null;
}

@model UCMS.WebSite.Models.SysNoticeModels.SysNoticeModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body class="dialog">
    <div class="tab-pane active" id="widget_tab1">
        @using (Html.BeginForm("Save", "SysNotice", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
        {
            @Html.HiddenFor(c => c.Id)
            <table class="formtab_user">
                <tbody>
                    <tr>
                        <th><font style="color:red;">*</font>标题：</th>
                        <td>
                            @Html.TextBoxFor(c => c.Title, new { @class = "input-medium" })
                        </td>
                    </tr>
                    <tr>
                        <th><font style="color:red;">*</font>是否公告：</th>
                        <td>
                            <label>
                                @Html.RadioButton("NoticeType", 1)
                                <font style="color:orangered"> 是</font>
                            </label>
                            &nbsp;&nbsp;&nbsp;
                            <label>
                                @Html.RadioButton("NoticeType", 0)
                                <font style="color:blue"> 否</font>
                            </label>
                            <span style="color:red;">注：公告同时只能设置一条</span>
                        </td>
                    </tr>
                    <tr>
                        <th><font style="color:red;">*</font>内容：</th>
                        <td style="padding-right:20px;">
                            @Html.TextAreaFor(c => c.Content, new { @style = "width:600px;height:280px;" })
                        </td>
                    </tr>
                </tbody>
            </table>
        }
    </div>
    <script src="~/Theme/js/jquery.validate.js"></script>
    <script src="~/Theme/js/jquery.form.js"></script>
    <script type="text/javascript">
        var editor;
        $(document).ready(function () {
            editor = KindEditor.create('textarea[name="Content"]', {
                autoHeightMode: false,
                items: [
                        'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold', 'italic', 'underline', 'strikethrough', 'lineheight',
                        'removeformat', '|',
                        'plainpaste', 'wordpaste', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist',
                        'insertunorderedlist', '|', 'emoticons', 'image', 'fullscreen'],
                afterCreate: function () {
                    this.loadPlugin('autoheight');
                },
                allowUpload: true,
                uploadJson: controller() + "UploadImage"
            });
        });
        function controller() {
            return '@Url.Content("~/Sys/SysNotice/")';
        }
        function Save()
        {
            $("#Content").attr("value", editor.html());
            if (editor.html() == "" || editor.html()==undefined)
            {
                $.jBox.tip("请输入公告内容！", "error");
            }
            if (validateForm()) {
                $("#documentForm").ajaxSubmit({
                    success: function (data) {
                        if (data.d=="1") {
                            $.jBox.close();
                            window.location.href = controller()+"Index";
                            $.jBox.tip("保存成功！", "success");
                        } else {
                            $.jBox.tip("保存失败！", "error");
                        }
                    }
                });
            }
        }
        function validateForm() {
            return $("#documentForm").validate({
                rules: {
                    Title: {
                        required: true,
                        maxlength: 50
                    },
                    Content: {
                        required: true,
                    }
                },
                messages: {
                    Title: {
                        required: "必填项",
                        maxlength: $.validator.format("不能大于{0}个字符")
                    },
                    Content: {
                        required: "必填项"
                    }
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                }
            }).form();
        }
    </script>
</body>
</html>

ERP.WebSite/Views/SysNotice/Detail.cshtml
@{
    Layout = null;
}

@model UCMS.WebSite.Models.SysNoticeModels.SysNoticeModel
    <div style="padding:10px;"> 
        <div style="text-align:center;font-weight:bold;">
            @Model.Title
        </div>
        <div>
            @Html.Raw(Model.Content)
        </div>
    </div>

ERP.WebSite/Views/SysNotice/Index.cshtml
@{
//Layout = null;
}

@model IEnumerable<UCMS.WebSite.Models.SysNoticeModels.SysNoticeModel>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>公告设置</title>
</head>
<body>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget box light-grey">
                <div class="widget-title">
                    <div class="actions">
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="Add()"><i class="icon-pencil"></i>&nbsp;新增</a>
                        <a class="btn btn-danger" href="javascript:void(0)" onclick="Delete()"><i class="icon-trash"></i>&nbsp;删除</a>
                    </div>
                </div>
                <div class="widget-body">
                    <table class="table-bordered table table-striped table-hover" id="tabInfo">
                        <thead>
                            <tr class="widget-title1">
                                <th style="width: 8px;"><input type="checkbox" class="group-checkable" onclick="SelectAll(this)" /></th>
                                <th>序号</th>
                                <th>标题</th>
                                <th>是否公告</th>
                                <th>创建时间</th>
                                <th style="width: 150px;">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count() > 0)
                            {
                                int index = 1;
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <input id="checkedId" name="checkedId" type="checkbox" value="@item.Id">
                                        </td>
                                        <td>@index</td>
                                        <td>@item.Title</td>
                                        <td>@Html.Raw(item.NoticeType==1?"是":"否")</td>
                                        <td>@item.CreateTime</td>
                                        <td style='text-align:center'>
                                            <a href="javascript:void(0)" onclick="Add('@item.Id')">修改</a> | 
                                            <a href="javascript:void(0)" onclick="Detail('@item.Id')">查看</a>
                                        </td>
                                    </tr>
                                    index++;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="10" style="text-align:center">
                                        暂无数据。。。
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script src="~/Theme/plugins/kindeditor/kindeditor-min.js"></script>
    <script src="~/Theme/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        function controller() {
            return '@Url.Content("~/Sys/SysNotice/")';
        }
        function Add(Id) {
            Id = Id == undefined ? "" : Id;
            $.jBox.open("get:" + controller() + "Create?Id=" + Id, "编辑公告", 750, 500, {
                buttons: { '确定': true, '关闭': false }, submit: function (v, h, f) {
                    if (v == true) {
                        window.Save();
                        return false;
                    } else {
                        return true;
                    }
                }
            });
        }
        function Detail(Id) {
            Id = Id == undefined ? "" : Id;
            $.jBox.open("get:" + controller() + "Detail?Id=" + Id, "查看公告", 700, 500, {
                buttons: {  '关闭': false }, submit: function (v, h, f) {
                    return true;
                }
            });
        }

        function SelectAll(item) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", true);
            } else {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", false);
            }
        }
        function Delete() {
            var items = [];
            $("#tabInfo").children("tbody").find("input[type='checkbox']").each(function (i, item) {
                var flag = $(item).attr("checked");
                if (flag || flag == "checked") {
                    var cateNum = $(item).val();
                    items.push(cateNum);
                }
            });
            if (items.length == 0) {
                $.jBox.tip("请选择要删除的数据", "warn");
                return false;
            }

            var submit = function (v, h, f) {
                if (v == "ok") {
                    var param = {};
                    param["checkedId"] = items.join(",");

                    $.ajax({
                        url: controller()+"Delete",
                        data: param,
                        type: "post",
                        dataType: "json",
                        success: function (result) {
                            if (result.d == "1") {
                                $.jBox.tip("删除成功！", "success");
                                location.reload()
                            } else {
                                $.jBox.tip("删除失败！", "error");
                            }
                        }
                    });
                }
            }
            $.jBox.confirm("确认要做删除操作？", "提示", submit);
        }
    </script>
</body>
</html>