ERP.WebSite/Controllers/Car/CarBrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCMS.WebSite.Controllers.Car
{
    public class CarBrandController : Controller
    {
        Provider.CarBrandProvider provider = new Provider.CarBrandProvider();
        // GET: CarBrand
        [Extension.UserAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        [Extension.UserAuthorize(ActionName = "Index")]
        public ActionResult GetList(Common.PagingModels paging, string Search)
        {
            var model = new List<Models.CarBrandModels.CarBrandModel>();
            var list = provider.GetList(paging, Search);
            foreach (var item in list)
            {
                model.Add(new Models.CarBrandModels.CarBrandModel
                {
                    Id = item.Id.ToString(),
                    BrandSort=item.BrandSort,
                    BrandName=item.BrandName,
                    Initial=item.Initial
                });
            }
            var json = new
            {
                Data = model,
                RowCount = paging.totalrows
            };
            return Content(Newtonsoft.Json.JsonConvert.SerializeObject(json));
        }
        [Extension.UserAuthorize]
        public ActionResult Create(long? Id)
        {
            var model = new Models.CarBrandModels.CarBrandModel();
            if (Id != null)
            {
                var cache = new Cache.CarBrandCache().Get(Common.FormsTicket.SystemCode).Where(c => c.Id == Id).FirstOrDefault();
                model = new Models.CarBrandModels.CarBrandModel
                {
                    Id=cache.Id.ToString(),
                    BrandSort=cache.BrandSort,
                    BrandName=cache.BrandName
                };
            }
            return View(model);
        }
        [Extension.UserAuthorize(ActionName = "Create")]
        public ActionResult Save(Models.CarBrandModels.CarBrandModel model)
        {
            var group = new UCMS.Entitys.CarBrand()
            {
                Id =Common.ToolHelper.ConvertToLong(model.Id),
                BrandSort = model.BrandSort,
                BrandName = model.BrandName,
                Initial= Common.SpellHelper.GetSpellCode(model.BrandName.Trim()),
                IsDelete = (int)Common.EnumModel.EIsDelete.NotDelete,
                TimeStamp = DateTime.Now,
            };
            var line = provider.Edit(group);
            if (line > 0)
            {
                //删除缓存
                new Cache.CarBrandCache().Delete(Common.FormsTicket.SystemCode);
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }
        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="checkedId"></param>
        /// <returns></returns>
        [Extension.UserAuthorize]
        public ActionResult Delete(string checkedId)
        {
            var ids = new List<long>();
            foreach (var item in checkedId.Split(','))
            {
                ids.Add(Common.ToolHelper.ConvertToLong(item));
            }
            var line = 0;
            if (ids.Count > 0)
            {
                line = provider.Delete(ids);
                if (line > 0)
                {
                    //删除缓存
                    new Cache.CarBrandCache().Delete(Common.FormsTicket.SystemCode);
                }
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }
    }
}

ERP.WebSite/Views/CarBrand/Create.cshtml
@{
    Layout = null;
}

@model UCMS.WebSite.Models.CarBrandModels.CarBrandModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body class="dialog">
    <div class="tab-pane active" id="widget_tab1">
        @using (Html.BeginForm("Save", "CarBrand", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
        {
            @Html.HiddenFor(c => c.Id)
            <table class="formtab_user">
                <tbody>
                    <tr>
                        <th>排序：</th>
                        <td>
                            @Html.TextBoxFor(c => c.BrandSort, new { @class = "input-medium" })
                        </td>
                    </tr>
                    <tr>
                        <th>品牌名称：</th>
                        <td>
                            @Html.TextBoxFor(c => c.BrandName, new { @class = "input-medium" })
                        </td>
                    </tr>
                </tbody>
            </table>
        }
    </div>
    <script src="~/Theme/js/jquery.validate.js"></script>
    <script src="~/Theme/js/jquery.form.js"></script>
    <script type="text/javascript">
        function controller() {
            return '@Url.Content("~/Car/CarBrand/")';
        }
        function Save()
        {
            if (validateForm()) {
                $("#documentForm").ajaxSubmit({
                    success: function (data) {
                        if (data.d=="1") {
                            $.jBox.close();
                            window.location.href = controller()+"Index";
                            $.jBox.tip("保存成功！", "success");
                        } else {
                            $.jBox.tip("保存失败！", "error");
                        }
                    }
                });
            }
        }
        function validateForm() {
            return $("#documentForm").validate({
                rules: {
                    BrandName: {
                        required: true,
                        maxlength: 20
                    },
                    BrandSort: {
                        number: true
                    }
                },
                messages: {
                    BrandName: {
                        required: "必填项",
                        maxlength: $.validator.format("不能大于{0}个字符")
                    },
                    BrandSort: {
                        number: "请输入数字"
                    }
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                }
            }).form();
        }
    </script>
</body>
</html>

ERP.WebSite/Views/CarBrand/Index.cshtml
@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>品牌设置</title>
</head>
<body>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget box light-grey">
                <div class="widget-title">
                    <div class="actions">
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="Add()"><i class="icon-pencil"></i>&nbsp;新增</a>
                        <a class="btn btn-danger" href="javascript:void(0)" onclick="Delete()"><i class="icon-trash"></i>&nbsp;删除</a>
                    </div>
                </div>
                <div class="widget-body">
                    <div class="row-fluid">
                        <form class="form-horizontal" action="javascript:void(0)">
                            <div class="control-group">
                                <div class="controls controls-cus">
                                    <input id="txtSearch" type="text" class="input-xlarge" style="width:220px;" />
                                    <a id="gritter-remove-all" class="btn btn-info" href="javascript:void(0)" onclick="PageClick(1)"><i class="icon-search"></i>&nbsp;搜索</a>
                                </div>
                            </div>
                        </form>
                    </div>
                    <table class="table-bordered table table-striped table-hover" id="tabInfo">
                        <thead>
                            <tr class="widget-title1">
                                <th style="width: 8px;"><input type="checkbox" class="group-checkable" onclick="SelectAll(this)" /></th>
                                <th>排序号</th>
                                <th>品牌名称</th>
                                <th style="width: 150px;">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                                <tr>
                                    <td colspan="10" style="text-align:center">
                                        暂无数据。。。
                                    </td>
                                </tr>
                        </tbody>
                    </table>
                    <div class="row-fluid" id="mypager">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            //$(".widget").css("height", ($(window.parent.document).height() - 150));
            //$(".widget").css("overflow-y", "scroll");
            PageClick(1);
        });
        function PageClick(pageIndex, pageSize) {
            erp.loading();
            pageSize = pageSize == undefined ? 10 : pageSize;
            var search = $("#txtSearch").val();
            var param = {};
            param["page"] = pageIndex;
            param["rows"] = pageSize;
            param["search"] = search;

            $.ajax({
                url: controller() + "GetList",
                data: param,
                type: "post",
                dataType: "json",
                success: function (result) {
                    var json = result;
                    var Html = "";
                    if (json.Data != undefined && json.Data.length > 0) {
                        $(json.Data).each(function (i, item) {
                            Html += "<tr class=\"odd gradeX\">";
                            Html += "<td>";
                            Html += '<input id="checkedId" name="checkedId" type="checkbox" value="' + item.Id + '">';
                            Html += "</td>";
                            Html += "<td>" + item.BrandSort + "</td>";
                            Html += "<td>" + item.BrandName + "</td>";
                            Html += "<td style='text-align:center'>";
                            Html += "<a href=\"javascript:void(0)\" onclick=\"Add('" + item.Id + "')\">修改</a>";
                            Html += "</td>";
                            Html += "</tr>";
                        });
                    }
                    else {
                        Html += '<tr><td colspan="10" style="text-align:center">暂无数据</td></tr>';
                    }
                    $("#tabInfo tbody").html(Html);
                    $("#mypager").pager({ pagenumber: pageIndex, recordCount: json.RowCount, pageSize: pageSize, buttonClickCallback: PageClick });
                }
            });
        }
        function controller() {
            return '@Url.Content("~/Car/CarBrand/")';
        }
        function Add(Id) {
            Id = Id == undefined ? "" : Id;
            $.jBox.open("get:" + controller() + "Create?Id=" + Id, "编辑品牌", 450, 250, {
                buttons: { '确定': true, '关闭': false }, submit: function (v, h, f) {
                    if (v == true) {
                        window.Save();
                        return false;
                    } else {
                        return true;
                    }
                }
            });
        }

        function SelectAll(item) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", true);
            } else {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", false);
            }
        }
        function Delete() {
            var items = [];
            $("#tabInfo").children("tbody").find("input[type='checkbox']").each(function (i, item) {
                var flag = $(item).attr("checked");
                if (flag || flag == "checked") {
                    var cateNum = $(item).val();
                    items.push(cateNum);
                }
            });
            if (items.length == 0) {
                $.jBox.tip("请选择要删除的数据", "warn");
                return false;
            }

            var submit = function (v, h, f) {
                if (v == "ok") {
                    var param = {};
                    param["checkedId"] = items.join(",");

                    $.ajax({
                        url: controller()+"Delete",
                        data: param,
                        type: "post",
                        dataType: "json",
                        success: function (result) {
                            if (result.d == "1") {
                                $.jBox.tip("删除成功！", "success");
                                location.reload()
                            } else {
                                $.jBox.tip("删除失败！", "error");
                            }
                        }
                    });
                }
            }
            $.jBox.confirm("确认要做删除操作？", "提示", submit);
        }
    </script>
</body>
</html>