ERP.WebSite/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UCMS.Common;

namespace UCMS.WebSite.Controllers
{
    public class CommonController : Controller
    {
        // GET: Common
        public ActionResult GetAreaItem(long? AreaId)
        {
            if (AreaId == null)
            {
                return Content("");
            }
            var AreaItem = UserControl.SelectItem.AreaItem(AreaId.Value, false, true);
            return Json(AreaItem);
        }

        public ActionResult GetUploadToken()
        {
          string token =  QiniuHelper.GetUploadToken();
          
            return Json(new
            {
                FileConfig.AccessKey,
                FileConfig.SecretKey,
                FileConfig.Bucket,
                Token = token


            },JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetCarImgPath(string ext)
        {
           var  fileId = PrimaryKey.GetHashCodeID.ToString();
            var filePath = Common.FileConfig.CarPhotoPath;
            var frst = filePath.Substring(0, 1);
            var fp = "";
            if (frst == "/")
            {
                fp = filePath.Substring(1, filePath.Length - 1);
            }
            var fname = string.Format("{0}/{1}/{2}", fp, fileId.Substring(0, 4), fileId.Substring(4) + ext);


            //var folderName = fileId.Substring(0, 4);
            //var fileName = fileId.Substring(4);
            //var keyfilePath = string.Format("{0}/{1}/", Common.FileConfig.CarPhotoPath, folderName);
            return Json(new
            {
               key = fname,
               name = fileId + ext

            }, JsonRequestBehavior.AllowGet);
        }
    }
}

ERP.WebSite/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace UCMS.WebSite.Controllers
{
    public class MobileController : Controller
    {
        Provider.CarInfoProvider provider = new Provider.CarInfoProvider();
        // GET: Mobile
        public ActionResult Index(string HopePrice, string UseYears, string CarType, string Search)
        {
            SetUser();
            #region 下拉
            var PriceItem = new List<SelectListItem>();
            PriceItem.Add(new SelectListItem { Text = "价格", Value = "0", Selected = string.IsNullOrEmpty(HopePrice) ? true : HopePrice == "0" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "5万以下", Value = "1", Selected = HopePrice == "1" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "5-10万", Value = "2", Selected = HopePrice == "2" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "10-15万", Value = "3", Selected = HopePrice == "3" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "15-25万", Value = "4", Selected = HopePrice == "4" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "25-40万", Value = "5", Selected = HopePrice == "5" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "40-50万", Value = "6", Selected = HopePrice == "6" ? true : false });
            PriceItem.Add(new SelectListItem { Text = "50万以上", Value = "7", Selected = HopePrice == "7" ? true : false });

            var YearItme = new List<SelectListItem>();
            YearItme.Add(new SelectListItem { Text = "车龄", Value = "0", Selected = string.IsNullOrEmpty(UseYears) ? true : UseYears == "0" ? true : false });
            YearItme.Add(new SelectListItem { Text = "1年内", Value = "1", Selected = UseYears == "1" ? true : false });
            YearItme.Add(new SelectListItem { Text = "1-2年", Value = "2", Selected = UseYears == "2" ? true : false });
            YearItme.Add(new SelectListItem { Text = "3-5年", Value = "3", Selected = UseYears == "3" ? true : false });
            YearItme.Add(new SelectListItem { Text = "5年以上", Value = "4", Selected = UseYears == "4" ? true : false });

            var TypeItem = CarTypeItem(Common.ToolHelper.ConvertToLong(CarType), true);
            #endregion
            ViewBag.PriceItem = PriceItem;
            ViewBag.YearItme = YearItme;
            ViewBag.TypeItem = TypeItem;
            var list = provider.GetList(Common.ToolHelper.ConvertToLong(CarType), Common.ToolHelper.ConvertToInt(UseYears), Common.ToolHelper.ConvertToInt(HopePrice), 1, Search).ToList();
            foreach (var item in list)
            {
                item.PhotoURL = new Common.FileHelper().GetFileUrl(item.PhotoURL, Common.FileConfig.CarPhotoPath, this.HttpContext);
            }
            ViewBag.Search = Search;
            return View(list);
        }
        public void SetUser()
        {
            var str = "";
            if (Common.FormsTicket.UserId > 0)
            {
                var u = new Provider.UserBasisProvider().GetUser(Common.FormsTicket.UserId);
                str = "<div><a style='color: red;margin-right: 10px;'>" + u.RealName + "</a><a href='" + Url.Content("~/Mobile/Logout") + "'><font>退出</font></a></div>";
            }
            else
            {
                str = "<div><a href='" + Url.Content("~/Mobile/Login") + "'><span>登录</span></a></div>";
            }
            ViewBag.User = str;

            //系统配置
            var title = new Cache.SysSettingCache().Get(Common.FormsTicket.SystemCode);
            ViewBag.Title = title.SystemName;

        }
        #region 下拉框

        /// <summary>
        /// 车型下拉框
        /// </summary>
        /// <param name="TypeId"></param>
        /// <param name="IsShowAll"></param>
        /// <param name="IsSelect"></param>
        /// <returns></returns>
        public static List<SelectListItem> CarTypeItem(long TypeId, bool IsShowAll)
        {
            var list = new List<SelectListItem>();
            if (IsShowAll)
            {
                list.Insert(0, new SelectListItem() { Text = "车型", Value = "", Selected = false });
            }
            var tb = new Cache.CarTypeCache().Get(Common.FormsTicket.SystemCode);
            foreach (var item in tb)
            {
                list.Add(new SelectListItem
                {
                    Text = item.TypeName,
                    Value = item.Id.ToString()
                });
            }
            foreach (var item in list)
            {
                if (item.Value == TypeId.ToString())
                {
                    item.Selected = true;
                    break;
                }
            }
            return list;
        }
        /// <summary>
        /// 品牌下拉框
        /// </summary>
        /// <param name="BrandId"></param>
        /// <param name="IsShowAll"></param>
        /// <param name="IsSelect"></param>
        /// <returns></returns>
        public static List<SelectListItem> CarBrandItem(long BrandId, bool IsShowAll, bool IsSelect = false)
        {
            var list = new List<SelectListItem>();
            if (IsShowAll)
            {
                list.Insert(0, new SelectListItem() { Text = "--全部--", Value = UCMS.Common.Constant.LONG_DEFAULT.ToString(), Selected = false });
            }
            if (IsSelect)
            {
                list.Insert(0, new SelectListItem() { Text = "--品牌--", Value = string.Empty, Selected = false });
            }
            var tb = new Cache.CarBrandCache().Get(Common.FormsTicket.SystemCode).OrderBy(c => c.Initial);
            foreach (var item in tb)
            {
                list.Add(new SelectListItem
                {
                    Text = item.Initial + " " + item.BrandName,
                    Value = item.Id.ToString()
                });
            }
            foreach (var item in list)
            {
                if (item.Value == BrandId.ToString())
                {
                    item.Selected = true;
                    break;
                }
            }
            return list;
        }
        /// <summary>
        /// 车系下拉框
        /// </summary>
        /// <param name="BrandId"></param>
        /// <param name="IsShowAll"></param>
        /// <param name="IsSelect"></param>
        /// <returns></returns>
        public static List<SelectListItem> CarSeriesItem(long BrandId, long SeriesId, bool IsShowAll, bool IsSelect = false)
        {
            var list = new List<SelectListItem>();
            if (IsShowAll)
            {
                list.Insert(0, new SelectListItem() { Text = "--全部--", Value = UCMS.Common.Constant.LONG_DEFAULT.ToString(), Selected = false });
            }
            if (IsSelect)
            {
                list.Insert(0, new SelectListItem() { Text = "--车系--", Value = string.Empty, Selected = false });
            }
            var tb = new Cache.CarSeriesCache().Get(BrandId);
            foreach (var item in tb)
            {
                list.Add(new SelectListItem
                {
                    Text = item.SeriesName,
                    Value = item.Id.ToString()
                });
            }
            foreach (var item in list)
            {
                if (item.Value == SeriesId.ToString())
                {
                    item.Selected = true;
                    break;
                }
            }
            return list;
        }
        /// <summary>
        /// 车型下拉信息
        /// </summary>
        /// <param name="Id"></param>
        /// <returns></returns>
        public ActionResult GetItem(long Id)
        {
            var SeriesItem = CarSeriesItem(Id, 0, false, true);
            return Json(SeriesItem);
        }
        #endregion
        public ActionResult GetList(FormCollection collection)
        {
            var CarType = Common.ToolHelper.ConvertToLong(collection["CarType"]);
            var Search = collection["Search"];
            var UseYears = Common.ToolHelper.ConvertToInt(collection["UseYears"]);
            var HopePrice = Common.ToolHelper.ConvertToInt(collection["HopePrice"]);
            var page = Common.ToolHelper.ConvertToInt(collection["page"]);
            var list = provider.GetList(CarType, UseYears, HopePrice, page, Search);
            var str = new System.Text.StringBuilder();
            foreach (var item in list)
            {
                /*
                 * 
                            <li>
                                <a href="~/Home/carinfo?id=@item.Id">
                                    <table>
                                        <tr>
                                            <th><img src="@item.PhotoURL" /></th>
                                            <td style="width:62%;">
                                                <h1>车辆型号：@Html.Raw(item.BrandName + item.SeriesName + item.CarName)</h1><br /><span>@item.Odometer / @Html.Raw(item.LicenseTime.ToString("yyyy-M"))</span><br /><label>￥@Html.Raw(item.RetailPrice)万元</label>
                                            </td>
                                        </tr>
                                    </table>
                                </a>
                            </li>
                 */
                str.Append("<li>");
                str.Append("<a href='/Home/carinfo?id=" + item.Id + "'>");
                str.Append("<table>");
                str.Append("<tr>");
                str.Append("<th><img src=" + new Common.FileHelper().GetFileUrl(item.PhotoURL, Common.FileConfig.CarPhotoPath, this.HttpContext) + " /></th>");
                str.Append("<td style='width:62%;'>");

ERP.WebSite/Views/Mobile/AuditInfo.cshtml
@{
    Layout = null;
}
@model UCMS.WebSite.Models.CarInfoModels.CarInfoModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>车源信息</title>
    <link href="~/Content/base.css" rel="stylesheet" />
    <link href="~/Content/cs.css" rel="stylesheet" />
    <link href="~/Content/lanrenzhijia.css" rel="stylesheet" />
    <script src="~/Theme/js/jquery-1.8.3.min.js"></script>
    <script src="~/Theme/js/jweixin-1.2.0.js"></script>
    <script src="~/Theme/js/function.js"></script>
</head>
<body>
    @using (Html.BeginForm("Audit", "Mobile", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
    {
        @Html.HiddenFor(c => c.Id)
        <div class="carinfo clearfix">
            <div class="carinfo3t clearfix"><a href="javascript:history.go(-1)">《 审核列表</a></div>
            <div class="carinfo3 clearfix">
                <table>
                    <tbody>
                        @*<tr>
                            <th>车辆识别码：</th>
                            <td>
                                @Html.Raw(Model.VIN)
                            </td>
                        </tr>
                        <tr>
                            <th>行驶证：</th>
                            <td>
                                <img style="width:100px;height:110px;" src="@Model.VehicleLicense" />
                            </td>
                        </tr>*@
                        <tr>
                            <th>车型：</th>
                            <td>
                                @Html.Raw(Model.TypeName)
                            </td>
                        </tr>
                        <tr>
                            <th>品牌：</th>
                            <td>
                                @Html.Raw(Model.BrandName + Model.SeriesName + Model.CarName)
                            </td>
                        </tr>
                        <tr>
                            <th>车源主图：</th>
                            <td>
                                <img style="width:100px;height:110px;" src="@Model.PhotoURL" />
                            </td>
                        </tr>
                        <tr>
                            <th>车源图片：</th>
                            <td id="ImgContent">
                                @if (Model.Photo != null && Model.Photo.Count > 0)
                                {
                                    foreach (var item in Model.Photo)
                                    {
                                        <div>
                                            <img style="width:100px;height:110px;" src="@item.URL" />
                                        </div>
                                    }
                                }
                            </td>
                        </tr>
                        <tr>
                            <th>车体颜色：</th>
                            <td>
                                @Html.Raw(Model.CarColor)
                            </td>
                        </tr>
                        <tr>
                            <th>车主报价：</th>
                            <td>
                                @Html.Raw(Model.RetailPrice)
                                <span>（万元）</span>
                            </td>
                        </tr>
                        <tr>
                            <th>上牌日期：</th>
                            <td>
                                @Html.Raw(Model.LicenseTime.ToString("yyyy-MM"))
                            </td>
                        </tr>
                        <tr>
                            <th>表显里程：</th>
                            <td>
                                @Html.Raw(Model.Odometer)
                            </td>
                        </tr>
                        <tr>
                            <th>排气量：</th>
                            <td>
                                @Html.Raw(Model.SweptVolume)
                            </td>
                        </tr>
                        <tr>
                            <th>排放标准：</th>
                            <td>
                                @Html.Raw(UCMS.Common.EnumHelper.GetEnumName<UCMS.Common.EnumModel.EEmissionStandards>(Model.EmissionStandards))
                            </td>
                        </tr>
                        <tr>
                            <th>国产进口：</th>
                            <td>
                                @Html.Raw(UCMS.Common.EnumHelper.GetEnumName<UCMS.Common.EnumModel.EProductAddress>(Model.ProductAddress))
                            </td>
                        </tr>
                        <tr>
                            <th>变速器：</th>
                            <td>
                                @Html.Raw(UCMS.Common.EnumHelper.GetEnumName<UCMS.Common.EnumModel.ETransmission>(Model.Transmission))
                            </td>
                        </tr>
                        <tr>
                            <th>燃料：</th>
                            <td>
                                @Html.Raw(UCMS.Common.EnumHelper.GetEnumName<UCMS.Common.EnumModel.EFuelType>(Model.Fuel))
                            </td>
                        </tr>
                        <tr>
                            <th>车检报告：</th>
                            <td>
                                <img style="width:100px;height:110px;" src="@Model.TestReport" />
                            </td>
                        </tr>
                        <tr>
                            <th>具体说明：</th>
                            <td>
                                @Html.Raw(Model.Remark)
                            </td>
                        </tr>
                        <tr>
                            <th>审核意见：</th>
                            <td>
                                @Html.TextArea("AuditExplan", "")
                                @Html.Hidden("Status", "")
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="bgLine clearfix">&nbsp;</div>
        </div>
        <div class="bottom">
            <table style="height:30px;">
                <tbody>
                    <tr>
                        <td><a id="submit">通过</a></td>
                        <td><a id="noSubmit">不通过</a></td>
                        <td><a href="javascript:history.go(-1)">返回</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <script src="~/Theme/js/jquery.form.js"></script>
        <script>
        $(document).ready(function () {
            //保存
            $("#submit").click(function () {
                $("#Status").val("1");
                Save();
            });
            $("#noSubmit").click(function () {
                $("#Status").val("2");
                Save();
            });
        });
        function Save()
        {
            $("#documentForm").ajaxSubmit({
                success: function (data) {
                    if (data.d == "1") {
                        window.location.href = controller() + "/AuditList";
                    } else {
                        alert("审核失败！");
                    }
                }
            });
        }
        function controller() {
            return '@Url.Content("~/Mobile/")';
        }
        </script>
    }
</body>
</html>

ERP.WebSite/Views/Mobile/AuditList.cshtml
@{
    Layout = null;
}

@model IEnumerable<UCMS.Entitys.CarInfo>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>审核列表</title>
    <link href="~/Content/base.css" rel="stylesheet" />
    <link href="~/Content/cs.css" rel="stylesheet" />
    <link href="~/Content/lanrenzhijia.css" rel="stylesheet" />
    <script src="~/Theme/js/jquery-1.8.3.min.js"></script>
    <script src="~/Theme/js/jweixin-1.2.0.js"></script>
    <script src="~/Theme/js/function.js"></script>
</head>
<body>
    @using (Html.BeginForm("GetAuditList", "Mobile", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
    {
        <div class="w floatcenter clearfix">
            <div class="top">
                <a href="~/Mobile"><b style="line-height:30px;margin: 5px;">@ViewBag.Title</b></a>
                @Html.Raw(ViewBag.User)
            </div>
            <div class="carlist">
                <div class="carlist1 clearfix">
                    <ul id="carList">
                        @foreach (var item in Model)
                        {
                            <li>
                                <table>
                                    <tr>
                                        <th><img src="@item.PhotoURL" /></th>
                                        <td style="width:62%;">
                                            <h1>车辆型号：@Html.Raw(item.BrandName + item.SeriesName + item.CarName)</h1><br />
                                            <span>@item.Odometer / @Html.Raw(item.LicenseTime.ToString("yyyy-M"))</span><br />
                                            <label>￥@Html.Raw(item.RetailPrice)万元</label>
                                            <span style="display: inline-block;margin-left: 30px;">
                                                <a href="~/Mobile/AuditInfo?id=@item.Id">审核</a>
                                            </span>
                                        </td>
                                    </tr>
                                </table>
                            </li>
                        }
                    </ul>
                </div>
                <div class="more clearfix" id="more">
                    <input type="button" onclick="GetCarList2('more', 'carList', currPage)" value="按住上拉查看更多" />
                </div>
                <script type="text/javascript">
                    $(window).scroll(function () {
                        var scrollTop = $(this).scrollTop();
                        var scrollHeight = $(document).height();
                        var windowHeight = $(this).height();
                        if (scrollTop + windowHeight == scrollHeight) {
                            if ($("#iMove").val() != "没有了")
                            {
                                GetCarList2('more', 'carList', currPage);
                            }
                        }
                    });
                </script>
            </div>
            <div class="bgLine clearfix">&nbsp;</div>
        </div>

        <div class="bottom">
            <table style="height:30px;">
                <tbody>
                    <tr>
                        <td><a href="~/Mobile">首页</a></td>
                        <td><a href="~/Mobile/MyCar">我的车源</a></td>
                        <td><a href="#" style="color:red;">审核车源</a></td>
                        <td><a href="~/Mobile/Notice">公告</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="piao">
            <div onclick="$(window).scrollTop(0);">顶部</div>
        </div>
    }
</body>
</html>

ERP.WebSite/Views/Mobile/Index.cshtml
@{
    Layout = null;
}
@model IEnumerable<UCMS.Entitys.CarInfo>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/base.css" rel="stylesheet" />
    <link href="~/Content/cs.css" rel="stylesheet" />
    <link href="~/Content/lanrenzhijia.css" rel="stylesheet" />
    <script src="~/Theme/js/jquery-1.8.3.min.js"></script>
    <script src="~/Theme/js/jweixin-1.2.0.js"></script>
    <script src="~/Theme/js/function.js"></script>
    <style>

    </style>
</head>
<body>
    @using (Html.BeginForm("Index", "Mobile", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
    {
        <div class="w floatcenter clearfix">
            <div class="top">
                <a href="#"><b style="line-height:30px;margin: 5px;">@ViewBag.Title</b></a>
                @Html.Raw(ViewBag.User)
            </div>
            <div class="carlist">
                <div class="carlist_s clearfix">
                    <table>
                        <tbody>
                            <tr>
                                <td>
                                    @Html.DropDownList("HopePrice", ViewBag.PriceItem as List<SelectListItem>,new { onchange= "document.documentForm.submit()" })
                                </td>
                                <td>
                                    @Html.DropDownList("UseYears", ViewBag.YearItme as List<SelectListItem>, new { onchange = "document.documentForm.submit()" })
                                </td>
                                <td>
                                    @Html.DropDownList("CarType", ViewBag.TypeItem as List<SelectListItem>, new { onchange = "document.documentForm.submit()" })
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="carsearch clearfix">
                    <input name="Search" type="text" id="Search" class="carsearch1" placeholder="请在这里输入关键字" value="@ViewBag.Search">
                    <input type="image" name="ibtSearch" id="ibtSearch" class="carsearch2" src="~/Content/Images/search.png" style="border-width:0px;">
                </div>
                <div class="carlist1 clearfix">
                    <ul id="carList">
                        @foreach (var item in Model)
                        {
                            <li>
                                <a href="~/Mobile/carinfo?id=@item.Id">
                                    <table>
                                        <tr>
                                            <th><img src="@item.PhotoURL" /></th>
                                            <td style="width:62%;">
                                                <h1>车辆型号：@Html.Raw(item.BrandName + item.SeriesName + item.CarName)</h1><br /><span>@item.Odometer / @Html.Raw(item.LicenseTime.ToString("yyyy-M"))</span><br /><label>￥@Html.Raw(item.RetailPrice)万元</label>
                                            </td>
                                        </tr>
                                    </table>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
                <div class="more clearfix" id="more">
                    <input type="button" onclick="GetCarList('more','carList',currPage)" value="按住上拉查看更多"/>
                </div>
                <script type="text/javascript">
                    $(window).scroll(function () {
                        var scrollTop = $(this).scrollTop();
                        var scrollHeight = $(document).height();
                        var windowHeight = $(this).height();
                        if (scrollTop + windowHeight == scrollHeight) {
                            if ($("#iMove").val() != "没有了") {
                                GetCarList('more', 'carList', currPage);
                            }
                        }
                    });
                </script>
            </div>
            <div class="bgLine clearfix">&nbsp;</div>
        </div>

        <div class="bottom">
            <table style="height:30px;">
                <tbody>
                    <tr>
                        <td><a href="#" style="color:red;">首页</a></td>
                        <td><a href="~/Mobile/MyCar">我的车源</a></td>
                        @if (UCMS.Common.FormsTicket.UserType == 1)
                        {
                            <td><a href="~/Mobile/AuditList">审核车源</a></td>
                        }
                        <td><a href="~/Mobile/Notice">公告</a></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="piao">
            <div onclick="$(window).scrollTop(0);">顶部</div>
        </div>
    }
</body>
</html>

ERP.WebSite/Views/Mobile/Test.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>表单小图片上传</title>
    <script src="http://code.jquery.com/jquery-1.4.1.min.js"></script>
    <script>var imgurl = "";
            function getPhoto(node) {
                var imgURL = "";
                try{
                    var file = null;
                    if(node.files && node.files[0] ){
                        file = node.files[0];
                    }else if(node.files && node.files.item(0)) {
                        file = node.files.item(0);
                    }
                    //Firefox 因安全性问题已无法直接通过input[file].value 获取完整的文件路径
                    try{
                        imgURL =  file.getAsDataURL();
                    }catch(e){
                        imgRUL = window.URL.createObjectURL(file);
                    }
                }catch(e){
                    if (node.files && node.files[0]) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            imgURL = e.target.result;
                        };
                        reader.readAsDataURL(node.files[0]);
                    }
                }
                creatImg(imgRUL,file.name);
                return imgURL;
            }

            function creatImg(imgRUL,fileName){
                console.log(fileName);
                $("input[name=key]").val(fileName);
                var textHtml = "<img src='"+imgRUL+"'width='40px' height='40px'/>";
                $("span").html(textHtml);
            }

            function upload(){
                $.ajax({
                    url: '@Url.Action("GetUploadToken", "Common")',
                    //data:{"key": $("input[name=key]").val()},
                    type: "GET",
                     success:function (data) {//请求成功后调用的函数
                         $("input[name=token]").val(data.Token);
                         $("input[name=key]").val(data.Bucket);
                           document.getElementById('form1').submit();
                     },
                     error:function () {//请求失败后调用的函数
                        console.log(err);
                     }
                 });
            }</script>
</head>
<body>
    <form id="form1" method="post" action="http://upload-z2.qiniup.com/"
          enctype="multipart/form-data">
        <input name="key" value="" type="hidden" />
        <input name="token" value="" type="hidden" />
        <input id="input-file" name="file" class="upload" type="file" value="" onchange="getPhoto(this)">
        <input type="button" value="上传" onclick="upload()">
    </form>
    <br />
    <span> </span>
</body>
</html>