ERP.WebSite/Controllers/Sys/RoleBasisController.cs
using EntityFramework.Extensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UCMS.WebSite.Controllers.Sys
{
    public class RoleBasisController : Controller
    {
        // GET: RoleBasis
        [Extension.UserAuthorize]
        public ActionResult Index()
        {
            var cache = new Cache.Sys_RoleBasisCache().Get(Common.FormsTicket.SystemCode);
            var list = new List<Models.RoleBasisModels.RoleBasisModel>();
            foreach (var item in cache)
            {
                list.Add(new Models.RoleBasisModels.RoleBasisModel {
                    Id=item.Id,
                    IsSystem=item.IsSystem,
                    RoleSort=item.RoleSort,
                    RoleCode=item.RoleCode,
                    RoleName=item.RoleName
                });
            }
            return View(list);
        }

        [Extension.UserAuthorize]
        public ActionResult Create(long? RoleId)
        {
            var model = new Models.RoleBasisModels.RoleBasisModel();
            if (RoleId != null)
            {
                var cache = new Cache.Sys_RoleBasisCache().Get(Common.FormsTicket.SystemCode).Where(c => c.Id == RoleId).FirstOrDefault();
                model = new Models.RoleBasisModels.RoleBasisModel
                {
                    Id = cache.Id,
                    RoleSort=cache.RoleSort,
                    IsSystem=cache.IsSystem,
                    RoleCode=cache.RoleCode,
                    RoleName=cache.RoleName
                };
            }
            return View(model);
        }
        [Extension.UserAuthorize(ActionName ="Create")]
        public ActionResult Save(Models.RoleBasisModels.RoleBasisModel model)
        {
            var role = new UCMS.Entitys.SysRoleBasis()
            {
                Id = model.Id,
                IsSystem =0,
                RoleName = model.RoleName == null ? "" : model.RoleName,
                RoleCode = model.RoleCode == null ? "" : model.RoleCode,
                RoleSort=model.RoleSort,
                IsDelete = 0,
                TimeStamp = DateTime.Now,
            };
            var db = new Entitys.UCMSContext();
            if (model.Id == 0)
            {
                role.Id = Common.PrimaryKey.GetHashCodeID;
                db.SysRoleBasis.Add(role);
            }
            else
            {
                db.Entry<Entitys.SysRoleBasis>(role).State = System.Data.Entity.EntityState.Modified;
            }
            var line = db.SaveChanges();
            if (line > 0)
            {
                //删除缓存
                new Cache.Sys_RoleBasisCache().Delete(Common.FormsTicket.SystemCode);
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }
        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="checkedId"></param>
        /// <returns></returns>
        [Extension.UserAuthorize]
        public ActionResult Delete(string checkedId)
        {
            var ids = new List<long>();
            foreach (var item in checkedId.Split(','))
            {
                ids.Add(Common.ToolHelper.ConvertToLong(item));
            }
            var line = 0;
            if (ids.Count > 0)
            {
                var db = new Entitys.UCMSContext();
                line = db.SysRoleBasis.Where(c => ids.Contains(c.Id)).Update(r => new Entitys.SysRoleBasis { IsDelete = 1 });
                if (line > 0)
                {
                    //删除缓存
                    new Cache.Sys_RoleBasisCache().Delete(Common.FormsTicket.SystemCode);
                }
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }
        #region 角色权限
        [Extension.UserAuthorize(ActionName = "Create")]
        public ActionResult RoleMenu(long? RoleId)
        {
            if (RoleId == null || RoleId == 0)
            {
                return Content("请重新操作！");
            }
            var list = new List<Models.RoleBasisModels.RoleMenuModel>();
            var menu = new Cache.Sys_MenuBasisCache().Get(Common.FormsTicket.SystemCode);
            var roleMenu = new Cache.Sys_RoleMenuCache().Get(RoleId.Value);

            var operate = new Cache.Sys_MenuOperateCache();
            var roleOp = new Cache.Sys_RoleOperateCache().Get(RoleId.Value);
            foreach (var item in menu.Where(c=>c.ParentId==Common.Constant.LONG_DEFAULT))
            {
                foreach (var mItem in menu.Where(c => c.ParentId == item.Id))
                {
                    var opList = new List<Models.RoleBasisModels.RoleOperateModel>();
                    foreach (var r in operate.Get(mItem.Id))
                    {
                        //操作码权限
                        var ro = roleOp.Where(c => c.OperateId == r.Id).FirstOrDefault();
                        opList.Add(new Models.RoleBasisModels.RoleOperateModel
                        {
                            OperateId = r.Id,
                            OperateName = r.OperateName,
                            MenuId=mItem.Id,
                            IsSelect = ro != null ? true : false,
                            Id = ro != null ? ro.Id : 0
                        });
                    }
                    //二级菜单
                    var m1 = roleMenu.Where(c => c.MenuId == mItem.Id).FirstOrDefault();
                    list.Add(new Models.RoleBasisModels.RoleMenuModel
                    {
                        MenuId = mItem.Id,
                        ParentId = mItem.ParentId,
                        MenuName = mItem.MenuName,
                        IsSelect = m1 != null ? true : false,
                        Id= m1 != null ? m1.Id:0,
                        OperateList = opList
                    });
                }
                //一级菜单
                var m = roleMenu.Where(c => c.MenuId == item.Id).FirstOrDefault();
                list.Add(new Models.RoleBasisModels.RoleMenuModel
                {
                    MenuId = item.Id,
                    ParentId = item.ParentId,
                    MenuName = item.MenuName,
                    IsSelect = m != null ? true : false,
                    Id = m != null ? m.Id : 0,
                });
            }
            ViewBag.RoleId = RoleId.Value;
            return View(list);
        }
        [Extension.UserAuthorize(ActionName = "Create")]
        [HttpPost]
        public ActionResult SaveRoleMenu(string checkedId,string RoleId)
        {
            var line = 0;
            if (!string.IsNullOrEmpty(checkedId)&& !string.IsNullOrEmpty(RoleId))
            {
                var temp = checkedId.Split(',');
                var roleMenu = new List<Entitys.SysRoleMenu>();
                var roleOperate = new List<Entitys.SysRoleOperate>();
                foreach (var item in temp)
                {
                    if (!string.IsNullOrEmpty(item))
                    {
                        var str = item.Split('_');
                        if (str[0] == "cm")
                        {
                            roleMenu.Add(new Entitys.SysRoleMenu
                            {
                                Id = Common.ToolHelper.ConvertToLong(str[2]),
                                MenuId = Common.ToolHelper.ConvertToLong(str[1]),
                                RoleId = Common.ToolHelper.ConvertToLong(RoleId),
                                TimeStamp = DateTime.Now,
                                IsDelete = 0,
                            });
                        }
                        else
                        {
                            roleOperate.Add(new Entitys.SysRoleOperate
                            {
                                Id = Common.ToolHelper.ConvertToLong(str[3]),
                                MenuId = Common.ToolHelper.ConvertToLong(str[1]),
                                OperateId= Common.ToolHelper.ConvertToLong(str[2]),
                                RoleId = Common.ToolHelper.ConvertToLong(RoleId),
                                TimeStamp = DateTime.Now,
                                IsDelete = 0,
                            });
                        }
                    }
                }
                line = new Provider.RoleBasisProvider().SetMenu(roleMenu, roleOperate);
                //删除缓存
                if (roleMenu.Count() > 0)
                {
                    new Cache.Sys_RoleMenuCache().Delete(Common.ToolHelper.ConvertToLong(RoleId));
                }
                if (roleOperate.Count() > 0)
                {
                    new Cache.Sys_RoleOperateCache().Delete(Common.ToolHelper.ConvertToLong(RoleId));
                }
            }
            return Json(new { d = line > 0 ? 1 : 0 });
        }
        #endregion
    }
}

ERP.WebSite/Views/RoleBasis/Create.cshtml
@{
    Layout = null;
}

@model UCMS.WebSite.Models.RoleBasisModels.RoleBasisModel
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body class="dialog">
    <div class="tab-pane active" id="widget_tab1">

        @using (Html.BeginForm("Save", "RoleBasis", FormMethod.Post, new { @id = "documentForm", @name = "documentForm" }))
        {
            @Html.HiddenFor(c => c.Id)
            <table class="formtab_user">
                <tbody>
                    <tr>
                        <th>角色编码：</th>
                        <td>
                            @Html.TextBoxFor(c => c.RoleCode, new { @class = "input-medium" })
                        </td>
                    </tr>
                    <tr>
                        <th>角色名称：</th>
                        <td>
                            @Html.TextBoxFor(c => c.RoleName, new { @class = "input-medium" })
                        </td>
                    </tr>
                    <tr>
                        <th>排序：</th>
                        <td>
                            @Html.TextBoxFor(c => c.RoleSort, new { @class = "input-medium" })
                        </td>
                    </tr>
                </tbody>
            </table>
        }
    </div>
    <script src="~/Theme/js/jquery.validate.js"></script>
    <script src="~/Theme/js/jquery.form.js"></script>
    <script type="text/javascript">
        function controller() {
            return '@Url.Content("~/Sys/RoleBasis/")';
        }
        function SaveOperate()
        {
            if (validateForm()) {
                $("#documentForm").ajaxSubmit({
                    success: function (data) {
                        if (data.d=="1") {
                            $.jBox.close();
                            window.location.href = controller()+"Index";
                            $.jBox.tip("保存成功！", "success");
                        } else {
                            $.jBox.tip("保存失败！", "error");
                        }
                    }
                });
            }
        }
        function validateForm() {
            return $("#documentForm").validate({
                rules: {
                    RoleCode: {
                        required: true,
                        maxlength: 20
                    },
                    RoleName: {
                        required: true,
                        maxlength: 20
                    },
                    RoleSort: {
                        number: true
                    }
                },
                messages: {
                    RoleCode: {
                        required: "请输入角色编码",
                        maxlength: $.validator.format("角色编码不能大于{0}个字符")
                    },
                    RoleName: {
                        required: "请输入角色名称",
                        maxlength: $.validator.format("角色名称不能大于{0}个字符")
                    },
                    RoleSort: {
                        number: "请输入数字"
                    }
                },
                errorPlacement: function (error, element) {
                    error.appendTo(element.parent());
                }
            }).form();
        }
    </script>
</body>
</html>

ERP.WebSite/Views/RoleBasis/Index.cshtml
@{
//Layout = null;
}
@model IEnumerable<UCMS.WebSite.Models.RoleBasisModels.RoleBasisModel>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>角色设置</title>
</head>
<body>
    <div class="row-fluid">
        <div class="span12">
            <div class="widget box light-grey">
                <div class="widget-title">
                    <div class="actions">
                        <a class="btn btn-primary" href="javascript:void(0)" onclick="Add()"><i class="icon-pencil"></i>&nbsp;新增</a>
                        <a class="btn btn-danger" href="javascript:void(0)" onclick="Delete()"><i class="icon-trash"></i>&nbsp;删除</a>
                    </div>
                </div>
                <div class="widget-body">
                    <table class="table-bordered table table-striped table-hover" id="tabInfo">
                        <thead>
                            <tr class="widget-title1">
                                <th style="width: 8px;"><input type="checkbox" class="group-checkable" onclick="SelectAll(this)" /></th>
                                <th>排序号</th>
                                <th>角色名称</th>
                                <th>角色编码</th>
                                <th style="width: 150px;">操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count() > 0)
                            {
                                foreach (var item in Model)
                                {
                                    if (item.IsSystem == 1)
                                    {
                                        <tr>
                                            <td>
                                            </td>
                                            <td>@item.RoleSort</td>
                                            <td>@item.RoleName</td>
                                            <td>@item.RoleCode</td>
                                            <td style='text-align:center'>
                                                <a href="javascript:void(0)" onclick="RoleMenu('@item.Id')">角色权限</a>
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                    <tr>
                                        <td>
                                            <input id="checkedId" name="checkedId" type="checkbox" value="@item.Id">
                                        </td>
                                        <td>@item.RoleSort</td>
                                        <td>@item.RoleName</td>
                                        <td>@item.RoleCode</td>
                                        <td style='text-align:center'>
                                            <a href="javascript:void(0)" onclick="Add('@item.Id')">修改</a> | 
                                            <a href="javascript:void(0)" onclick="RoleMenu('@item.Id')">角色权限</a>
                                        </td>
                                    </tr>
                                    }
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="10" style="text-align:center">
                                        暂无数据。。。
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <script>
        function controller() {
            return '@Url.Content("~/RoleBasis/")';
        }
        function Add(RoleId) {
            RoleId = RoleId == undefined ? "" : RoleId;
            $.jBox.open("get:" + controller() + "Create?RoleId=" + RoleId, "编辑角色", 500, 300, {
                buttons: { '确定': true, '关闭': false }, submit: function (v, h, f) {
                    if (v == true) {
                        //var iframeHtml = window.frames["documentForm"];//获取子窗口的句柄iframeHtml.ownerDocument.defaultView.SaveOperate
                        //iframeHtml.ownerDocument.defaultView.SaveOperate();
                        window.SaveOperate();//获取子窗口方法
                        return false;
                    } else {
                        return true;
                    }
                }
            });
        }

        function SelectAll(item) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", true);
            } else {
                $("#tabInfo").children("tbody").find("input[type='checkbox']").attr("checked", false);
            }
        }
        function Delete() {
            var items = [];
            $("#tabInfo").children("tbody").find("input[type='checkbox']").each(function (i, item) {
                var flag = $(item).attr("checked");
                if (flag || flag == "checked") {
                    var cateNum = $(item).val();
                    items.push(cateNum);
                }
            });
            if (items.length == 0) {
                $.jBox.tip("请选择要删除的数据", "warn");
                return false;
            }

            var submit = function (v, h, f) {
                if (v == "ok") {
                    var param = {};
                    param["checkedId"] = items.join(",");

                    $.ajax({
                        url:  controller()+"Delete",
                        data: param,
                        type: "post",
                        dataType: "json",
                        success: function (result) {
                            if (result.d == "1") {
                                $.jBox.tip("删除成功！", "success");
                                location.reload()
                            } else {
                                $.jBox.tip("删除失败！", "error");
                            }
                        }
                    });
                }
            }
            $.jBox.confirm("确认要做删除操作？", "提示", submit);
        }
        function RoleMenu(RoleId)
        {
            RoleId = RoleId == undefined ? "" : RoleId;
            $.jBox.open("get:" + controller() + "RoleMenu?RoleId=" + RoleId, "角色菜单", 600, 500, {
                buttons: { '确定': true, '关闭': false }, submit: function (v, h, f) {
                    if (v == true) {
                        window.SaveRoleMenu();//获取子窗口方法
                        return false;
                    } else {
                        return true;
                    }
                }
            });
        }
    </script>
</body>
</html>

ERP.WebSite/Views/RoleBasis/RoleMenu.cshtml
@{
    Layout = null;
}
@model IEnumerable<UCMS.WebSite.Models.RoleBasisModels.RoleMenuModel>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RoleMenu</title>
    <style>

        label {
            display: inline-block;
            margin: 0px;    
            line-height: 13px;
        }
        .treeview, .treeview ul {
            padding: 0;
            margin: 0;
            list-style: none;
            text-align: left;
        }
      .treeview input[type="checkbox"]{margin: 5px 0px 5px 5px;}
.treeview ul {
	background-color: white;
	margin-top: 0px;
}

.treeview .hitarea {
	background: url("../Theme/Images/tree/treeview-default.gif") -64px -25px no-repeat;
	height: 16px;
	width: 16px;
	margin-left: -16px;
	float: left;
	cursor: pointer;
}
/* fix for IE6 */
* html .hitarea {
	display: inline;
	float:none;
}

.treeview li { 
	margin: 0;
	padding: 3px 0pt 3px 18px;
}

.treeview a.selected {
	background-color: #eee;
}

#treecontrol { margin: 1em 0; display: none; }

.treeview .hover { color: red; cursor: pointer; }

.treeview li { background: url("../Theme/Images/tree/treeview-default-line.gif") 0 0 no-repeat;}
.treeview li.collapsable, .treeview li.expandable { background-position: 0 -176px; }

.treeview .expandable-hitarea { background-position: -80px -3px; }

.treeview li.last { background-position: 0 -1766px }
.treeview li.lastCollapsable, .treeview li.lastExpandable { background-image: url("../Theme/Images/tree/treeview-default.gif"); }  
.treeview li.lastCollapsable { background-position: 0 -111px }
.treeview li.lastExpandable { background-position: -32px -67px }

.treeview div.lastCollapsable-hitarea, .treeview div.lastExpandable-hitarea { background-position: 0; }

.treeview-red li { background-image: url("../Theme/Images/tree/treeview-red-line.gif"); }
.treeview-red .hitarea, .treeview-red li.lastCollapsable, .treeview-red li.lastExpandable { background-image: url("../Theme/Images/tree/treeview-red.gif"); } 

.treeview-black li { background-image: url("../Theme/Images/tree/treeview-black-line.gif"); }
.treeview-black .hitarea, .treeview-black li.lastCollapsable, .treeview-black li.lastExpandable { background-image: url("../Theme/Images/tree/treeview-black.gif"); }  

.treeview-gray li { background-image: url("../Theme/Images/tree/treeview-gray-line.gif"); }
.treeview-gray .hitarea, .treeview-gray li.lastCollapsable, .treeview-gray li.lastExpandable { background-image: url("../Theme/Images/tree/treeview-gray.gif"); } 

.treeview-famfamfam li { background-image: url("../Theme/Images/tree/treeview-famfamfam-line.gif"); }
.treeview-famfamfam .hitarea, .treeview-famfamfam li.lastCollapsable, .treeview-famfamfam li.lastExpandable { background-image: url("../Theme/Images/tree/treeview-famfamfam.gif"); }

        /*.filetree li {
            padding: 3px 0 2px 16px;
        }*/
        .filetree .folder, .filetree .file {
            padding: 1px 0 1px 16px;
        }
        .filetree .folder {
            background: url("../Theme/Images/tree/folder.gif") 0 0 no-repeat;
        }
        .filetree li.expandable label.folder {
            background: url("../../Theme/Images/tree/folder-closed.gif") 0 0 no-repeat;
        }
        .filetree .file {
            background: url("../Theme/Images/tree/file.gif") 0 0 no-repeat;
            cursor: pointer;
        }

    </style>
    <script src="~/Theme/js/jquery.treeview.min.js"></script>
</head>
<body class="dialog">
    <div class="tab-pane active" id="widget_tab1">
        <table class="formtab_user">
            <tbody>
                <tr>
                    <td>
                    </td>
                    <td style="vertical-align: top;">
                        <ul id="treeview" class="filetree">
                            @Html.Hidden("RoleId", ViewBag.RoleId as string)
                            @if (Model.Count() > decimal.Zero)
                            {
                                <li>
                                    <label>
                                        <input type="checkbox" onclick="SelectAll1(this)" />
                                        <span>全选</span>
                                    </label>
                                </li>
                                foreach (var item in Model.Where(c => c.ParentId == UCMS.Common.Constant.LONG_DEFAULT))
                                {
                                    <li>
                                        @Html.CheckBox("cm_" + item.MenuId, item.IsSelect, new { @value = item.Id, @onclick = "OneMenu(this)", change = "default" })
                                        <span class="folder">@item.MenuName</span>
                                        <ul>
                                            @foreach (var twoMenu in Model.Where(c => c.ParentId == item.MenuId))
                                            {
                                                <li>
                                                    @Html.CheckBox("cm_" + twoMenu.MenuId, twoMenu.IsSelect, new { @value = twoMenu.Id, @onclick = "TwoMenu(this,'"+item.MenuId+"')", change = "default" })
                                                    <label for="cm_@twoMenu.MenuId" class="file">@twoMenu.MenuName</label>
                                                    @foreach (var mp in twoMenu.OperateList)
                                                    {
                                                        @Html.CheckBox("co_"+twoMenu.MenuId+"_" + mp.OperateId, mp.IsSelect, new { @value = mp.Id, change = "default" })
                                                        string co = "co_" + twoMenu.MenuId + "_" + mp.OperateId;
                                                        <label for="@co" class="file">@mp.OperateName</label>
                                                    }
                                                </li>
                                            }
                                        </ul>
                                    </li>
                                }
                            }
                        </ul>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <script>
        $(document).ready(function () {
            $("#treeview").treeview();
            $(":checkbox").change(function () {
                InputChange($(this));
            });
        });
        function controller() {
            return '@Url.Content("~/Sys/RoleBasis/")';
        }
        function SelectAll1(item) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                CheckedChange($("#treeview").find("input[type='checkbox']"), true)
            } else {
                CheckedChange($("#treeview").find("input[type='checkbox']"), false)
            }
        }
        function OneMenu(item) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                CheckedChange($(item).parent().find("input[type='checkbox']"), true)
            } else {
                CheckedChange($(item).parent().find("input[type='checkbox']"), false)
            }
        }
        function TwoMenu(item,menuId) {
            var flag = $(item).attr("checked");
            if (flag || flag == "checked") {
                var pf = $("#cm_" + menuId).attr("checked");
                if (pf || pf == "checked") {
                }
                else {
                    $("#cm_" + menuId).attr("checked", true);
                    InputChange($("#cm_" + menuId));
                }
            }
        }
        //选中不选中
        function CheckedChange(all, bool) {
            $.each(all, function (i, val) {
                var change = $(this);
                //本身就已经是当前状态就不作记录变更
                if (bool)
                {
                    if (change.attr("checked") != "checked")
                    {
                        //记录变更
                        InputChange(change)
                    }
                }
                else
                {
                    if (change.attr("checked") == "checked") {
                        //记录变更
                        InputChange(change)
                    }
                }
                change.attr("checked", bool);
            });
        }
        //记录变更
        function InputChange(change)
        {
            if (change.attr("change") == "default") {
                change.attr("change", "change")
            }
            else {
                change.attr("change", "default")
            }
        }

        function SaveRoleMenu()
        {
            var pData = "";
            $.each($("#treeview").find("input[type='checkbox']"), function (i, val) {
                //在这处理修改后的权限   分 授权和取消权限
                var cb = $(this);
                if (cb.attr("change") == ("change")) {
                    //menuid_明细id_授权和取消权限
                    var temp = ',' + cb.attr("id") + '_' + cb.attr("value");
                    pData += temp;
                }
            });
            if (pData != "") {
                var param = {};
                param["checkedId"] = pData;
                param["RoleId"] = $("#RoleId").attr("value");

                $.ajax({
                    url: controller()+"SaveRoleMenu",
                    data: param,
                    type: "post",
                    dataType: "json",
                    success: function (result) {
                        if (result.d == "1") {
                            $.jBox.tip("设置成功！", "success");
                            $.jBox.close();
                        } else {
                            $.jBox.tip("设置失败！", "error");
                        }
                    }
                });
            }
        }
    </script>
</body>
</html>